[package]
name = "rid_macro_test"
version = "0.0.0"
edition = "2018"
publish = false

[workspace]

[lib]
doctest = false

[[bin]]
name = "rid_macro_test"
path = "main.rs"

[dependencies]
rid_macro = { path = "../rid-macro" }
