[package]
name = "rid_build"
version = "0.1.0"
authors = ["Thorsten Lorenz <thlorenz@gmx.de>"]
edition = "2018"

[dependencies]
rid_common = { path = "../rid-common" }
cbindgen = "0.18.0"
anyhow = "1.0.38"
