[package]
name = "rid_derive_test"
version = "0.0.0"
edition = "2018"
publish = false

[workspace]

[[bin]]
name = "rid_derive_test"
path = "main.rs"

[dependencies]
rid_derive = { path = "../rid-derive" }
